import os 

AZURE_OPENAI_API_KEY = os.getenv('AZURE_OPENAI_API_KEY')

DINO_INFER_CLASSES = [
    'algae',
    'animal',
    'barricade',
    'boat',
    'bus',
    'car',
    'cone',
    'dog',
    'door',
    'drain',
    'driveway',
    'emergency exit',
    'entrance',
    'excavator',
    'faregate',
    'fence',
    'fire',
    'fish',
    'guardrail',
    'helmet',
    'human',
    'jersey barrier',
    'junk',
    'lane',
    'leaves',
    'litter',
    'manhole',
    'motorcycle',
    'parking lot',
    'passage',
    'palanquin',
    'pipeline',
    'road marking',
    'ruler',
    # 'seat',
    'sidewalk',
    'smoke',
    'solar panel',
    'storage tank',
    'streetlight',
    'traffic light',
    'traffic sign',
    'tree',
    'truck',
    'vest',
    'weapon',
]

EASY_CLASSES_LIST = [
    'algae',
    'drain',
    'faregate',
    'fire',
    'guardrail',
    'palanquin',
    'solar panel',
    'storage tank',
    'weapon',
]

HARD_CLASSES_LIST = [ cat for cat in DINO_INFER_CLASSES if cat not in EASY_CLASSES_LIST]