all_classes_str =  'detention basin, park, substation, port, landslide, flooding, ponding, wounds, rock, weapon, twig, no smoking sign, palanquin, car, vehicle, motorcycle, bus, truck, lane, driveway, driveway entracne, driveway exit, paved shoulder, pavement defect, pavement patch, collapse, intersection, waiting area, passage, sidewalk, entrance, exit, emergency exit, vehicle door, road marking, streetlight, pole, transformer box, fence, graffiti, trees, building, traffic sign, traffic light, warning sign, people, human, bridge, fire, smoke, lighting, obstacle, waste, branch, lock, window, knife, firearm, wheelchair, stroller, dog, seat crutch, cane, fallen leaves, tire, trash, garbage, litter, helmet, vast, rope, traffic cone, sign, safety harness, safety belt, barricade, jersey barrier, guardrail, water gauge, ship, boat, levee, silt, waterway, tools, equipment, manhole cover, thermometer, flowmeter, steel, pipeline, tank, electric tower, transformer, oil stain, oil leakage, solar panel, animal, electric wire, bus stop, parking lot, door, faregate, platform, fish, algae, pavement crack'
all_classes = all_classes_str.split(', ')

all_classes = [
    'algae',
    'animal',
    'barricade',
    'boat',
    'branch',
    'bridge',
    'building',
    'bus',
    'bus stop',
    'cane',
    'car',
    'collapse',
    'detention basin',
    'dog',
    'door',
    'driveway',
    'driveway entrance',
    'driveway exit',
    'electric tower',
    'electric wire',
    'emergency exit',
    'entrance',
    'equipment',
    'exit',
    'fallen leaves',
    'faregate',
    'fence',
    'fire',
    'firearm',
    'fish',
    'flooding',
    'flowmeter',
    'garbage',
    'graffiti',
    'guardrail',
    'helmet',
    'human',
    'intersection',
    'jersey barrier',
    'knife',
    'landslide',
    'lane',
    'levee',
    'lighting',
    'litter',
    'lock',
    'manhole cover',
    'motorcycle',
    'no smoking sign',
    'obstacle',
    'oil leakage',
    'oil stain',
    'palanquin',
    'park',
    'parking lot',
    'passage',
    'paved shoulder',
    'pavement crack',
    'pavement defect',
    'pavement patch',
    'people',
    'pipeline',
    'platform',
    'pole',
    'ponding',
    'port',
    'road marking',
    'rock',
    'rope',
    'safety belt',
    'safety harness',
    'seat crutch',
    'ship',
    'sidewalk',
    'sign',
    'silt',
    'smoke',
    'solar panel',
    'steel',
    'streetlight',
    'stroller',
    'substation',
    'tank',
    'thermometer',
    'tire',
    'tools',
    'traffic cone',
    'traffic light',
    'traffic sign',
    'transformer',
    'transformer box',
    'trash',
    'trees',
    'truck',
    'twig',
    'life vest',
    'vehicle',
    'vehicle door',
    'waiting area',
    'warning sign',
    'waste',
    'water gauge',
    'waterway',
    'weapon',
    'wheelchair',
    'window',
    'wounds',
]
all_classes.sort()

all_classes_logseq = [f'[[{cls}]]' for cls in all_classes]
all_classes_logseq_concat = (' ').join(all_classes_logseq)
for i, cls in enumerate(all_classes):
    print(f"{cls}")
print(all_classes_logseq_concat)